### ISSUE TITLE
[Enhancement] Add `Geometry` related methods

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/PeyrSharp#1]
### Enhancement

Add `Geometry` related methods

### Other informations
- PeyrSharp.Core (namespace)
    - **Maths** (namespace)
        - [x] Geometry (namespace)
            - [x] Circle
                - [x] `constructor(double radius)`
                - [x] `Area`
                - [x] `Perimeter`
            - [x] Rectangle
                - [x] `constructor(double width, double height)`
                - [x] `Diagonal`
                - [x] `Area`
            - [x] Triangle
                - [x] `constructor(double s1, double s2, double s3)`
                - [x] `Area`
                - [x] `Perimeter`
                - [x] `CanBeBuilt`
                - [x] `Hypotenuse`
                - [x] `IsRight`
            - [x] Cube
                - [x] `constructor(double side, [double height])`
                - [x] `Volume`
                - [x] `Edge`
                - [x] `Area`
            - [x] Cylinder
                - [x] `constructor(double radius, double height)`
                - [x] `Volume`
                - [x] `Height`
                - [x] `BaseArea`
            - [x] Pyramid
                - [x] `constructor(double length, double width, double height)`
                - [x] `FromVolume()` (static)
                - [x] `FromWidthArea()` (static)
                - [x] `FromLengthArea()` (static)
                - [x] `Volume`
                - [x] `Height`
                - [x] `LengthBase`
                - [x] `WidthBase`
            - [x] Hexagon
                - [x] `constructor(double side)`
                - [x] `Area`
                - [x] `Perimeter`
            - [x] Diamond
                - [x] `constructor(double side|double diag1, double diag2)`
                - [x] `Area`
                - [x] `Perimeter`
            - [x] Sphere
                - [x] `constructor(double radius)`
                - [x] `Area`
                - [x] `Volume`
            - [x] Cone
                - [x] `constructor(double radius, double height)`
                - [x] `Volume`
